version: "3.3"

services:
  compute-env:
    image: learn:0.0.1
    container_name: learn-qxai
    networks:
      extnetwork:
    hostname: compute-env
    volumes:
      - ".:/app"
    cap_add:
      - SYS_PTRACE
    privileged: true
    entrypoint:
      - bash
      - -c
      - tail -f /dev/null && wait