version: "3.3"

services:
  compute-env:
    image: registry.aibee.cn/mall/ae-build.cpu:1.0.0.snap-shot
    container_name: learn-qxai
    networks:
      extnetwork:
    hostname: compute-env
    volumes:
      - ".:/app"
    cap_add:
      - SYS_PTRACE
    privileged: true
    entrypoint:
      - bash
      - -c
      - tail -f /dev/null && wait
networks:
    extnetwork:
        driver: bridge
        ipam:
            config:
            - subnet: 171.111.0.0/16  